### ISSUE TITLE
Join problem between acaps and natural earth dataframes 

### ISSUE THREAD

**Issue by hannahker** [mapaction/covid-19_acaps#9]
Error when trying to create the output df, due to null values in the geometry column of the joined df. I think this problem may be due to some rows in the acaps df not matching with natural earth. 

```
No logging configuration parameter. Using default.
Loading logging configuration from: C:\Users\Hannah\anaconda3\envs\covid-19_acaps\Lib\site-packages\hdx\utilities\logging_configuration.yml
INFO - 2020-10-15 18:22:46 - hdx.hdx_configuration - No HDX base configuration parameter. Using default base configuration file: C:\Users\Hannah\anaconda3\envs\covid-19_acaps\Lib\site-packages\hdx\hdx_base_configuration.yml.
INFO - 2020-10-15 18:22:46 - hdx.hdx_configuration - Loading HDX base configuration from: C:\Users\Hannah\anaconda3\envs\covid-19_acaps\Lib\site-packages\hdx\hdx_base_configuration.yml
INFO - 2020-10-15 18:22:46 - hdx.hdx_configuration - No HDX configuration parameter and no configuration file at default path: C:\Users\Hannah\.hdx_configuration.yml.
INFO - 2020-10-15 18:22:46 - hdx.hdx_configuration - Read only access to HDX: True
INFO - 2020-10-15 18:22:46 - root - Getting ACAPS and Natural Earth data
INFO - 2020-10-15 18:22:52 - root - Saved "ACAPS_COVID19_Government_Measures_Dataset.xlsx" to "C:\Users\Hannah\AppData\Local\Temp\covid19_acaps/ACAPS_COVID19_Government_Measures_Dataset.xlsx.XLSX"
INFO - 2020-10-15 18:22:52 - root - Moving dataset to Z:\charlie\2020-03-16-global-covid-19-response-group\GIS\1_Original_Data\ACAPS_Govt_Measures\20201015_ACAPS_COVID19_Government_Measures_Dataset.xlsx.XLSX
INFO - 2020-10-15 18:23:11 - root - Joining data
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main(args.cmf_path, debug=args.debug)
  File "main.py", line 49, in main
    df_output = get_df_output(df_acaps, df_naturalearth)
  File "main.py", line 108, in get_df_output
    df_output['geometry'] = df_output['geometry'].apply(lambda x: x.representative_point())
  File "C:\Users\Hannah\anaconda3\envs\covid-19_acaps\lib\site-packages\pandas\core\series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "main.py", line 108, in <lambda>
    df_output['geometry'] = df_output['geometry'].apply(lambda x: x.representative_point())
AttributeError: 'NoneType' object has no attribute 'representative_point'
```

**Comment by hannahker** [comment]
It looks like this is because of an error in the ISO codes in the published data. Armenia is now coded as AZW, rather than ARM, which results in an incomplete join with the Natural Earth data.
